"""One-time conversion of the purchased kitchen environment asset
(model/kitchen/Kitchen.obj, a Blender-free SketchUp OBJ export) into a set
of small per-material STL meshes plus a color manifest that
urdf_to_mjcf.py's _build_kitchen_import() reads to place them in the MJCF --
the same "many small flat-colored STL parts" approach the robot's own CAD
meshes already use (see loadHumanoidScene.ts's own comment: this app's
three.js loader only ever reads flat rgba per geom, never a texture),
rather than trying to get MuJoCo/three.js to honor the OBJ's own 134
materials and UV-mapped textures directly.

Run once (`python3 model/scripts/convert_kitchen_obj.py`) after replacing
the source OBJ; output is checked in under model/kitchen/meshes/ like any
other static build input, not regenerated by urdf_to_mjcf.py itself.

This is the *second* kitchen asset this pipeline has imported (the first,
model/kitchen/new+kitchen.obj, is superseded and no longer referenced --
per the user's own explicit call: this new import is meant to fully replace
the old procedural room *and* the first imported kitchen, not sit alongside
either). Unlike the first import, this one supplies its own floor/walls/
ceiling (Stucco_A02_Color_50cm_White, Flooring_Parquet_Parallel_H01_120cm)
and is used as the *entire* room -- so there's no footprint-based shell
exclusion here the way the first conversion had one.

Why split by material at all instead of loading the OBJ directly: a MuJoCo
<mesh> asset is one set of vertices/faces with, at most, one <material> --
it has no notion of an OBJ's per-face `usemtl` switches. trimesh's
group_material=True loader merges every face in the whole file sharing a
material into one combined mesh regardless of which of the source file's
22904 named sub-objects/groups it came from (confirmed: this file has 134
newmtl entries and loading it this way yields exactly 134 geometries) --
i.e. one mesh per *color*, not per individual utensil/component, which is
what keeps the geom count low enough to stay interactive rather than
emitting a separate mesh per one of the ~1000s of small named parts.

Excluded materials (17 of 134, see _SKIP_MATERIALS): a "Sumele_*" human
figure (hair/skin/dress/shoe/jewelry) that never appears in any of the
reference renders (model/kitchen/kitchen-scene-*.webp) -- almost certainly
a stock entourage figure left in the source file but hidden/unused in the
actual rendered views -- and nine unused "*_Milgard" window color-swatch
variants (Espresso/Classic_Brown/Tan/Tweed/Clay/Silver/Sand/Bronze/Ivory/
Fog), each only 4 faces, bundled into the window component's own definition
but not the one actually applied (White_Milgard, at 2454 faces and a
footprint matching the visible window, clearly is -- kept).

Axis handling: this OBJ is Y-up (SketchUp's OBJ exporter convention,
confirmed by inspecting the raw vertex data), matching three.js's own
convention but not this app's MJCF-side convention (MuJoCo worldbody is
Z-up). mj_x=obj_x, mj_y=-obj_z, mj_z=obj_y is a proper rotation (determinant
+1, verified below), not a mirror, so winding order/normals need no extra
correction -- then the whole room is recentered so its own floor-plan
bounding box sits centered on the world origin (a real point inside an
actual room, unlike the first import which had to be offset against a
separate, since-removed procedural room's own south wall).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import trimesh
from shapely.geometry import Polygon, box as shapely_box

KITCHEN_DIR = Path(__file__).resolve().parent.parent / "kitchen"
OBJ_PATH = KITCHEN_DIR / "Kitchen.obj"
MESHES_DIR = KITCHEN_DIR / "meshes"
MANIFEST_PATH = KITCHEN_DIR / "manifest.json"

_SKIP_MATERIALS = {
    "Sumele_Hair",
    "Sumele_Dress",
    "Sumele_Dress2",
    "Sumele_Dress3",
    "Sumele_Skin",
    "Sumele_Shoe",
    "Sumele_Jewelry",
    "Espresso_Milgard",
    "Classic_Brown_Milgard",
    "Tan_Milgard",
    "Tweed_Milgard",
    "Clay_Milgard",
    "Silver_Milgard",
    "Sand_Milgard",
    "Bronze_Milgard",
    "Ivory_Milgard",
    "Fog_Milgard",
    # These three share one huge, oddly-shaped combined mesh (~7x2x9m
    # bounding box). Tried re-including them on the theory that it was only
    # a *collision* problem (a bad convex hull from trimesh merging several
    # small, legitimate objects sharing one material name, e.g. a fruit
    # bowl) now moot since all kitchen meshes are visual-only -- confirmed
    # live that theory was wrong: re-included, they render as large, wrong
    # dark triangular stripes cutting across whole walls, not a fruit bowl
    # plus incidental scattered debris. Real broken/stray geometry in the
    # source file, not just a bounding-box artifact -- excluded again.
    "Translucent_Glass_Gray1",
    "Glass_Crystal",
    "Plastic_Simple_Blurry_Black",
    # The pendant lamps' own support chain (Mater_03_Met_Corrente) is real
    # and wanted; this is a separate straight rigid rod running the same
    # path right next to it (Mater_04_Fia__o -- Portuguese for "wiring") --
    # the user's own report of "a black stick" alongside the chain on both
    # hanging lamps. Dropped rather than recolored since there's nothing
    # useful for it to look like once the chain already reads correctly.
    "Luminaria_Pendente_110_Mater_04_Fia__o",
}

# A perfectly flat (zero-thickness) combined mesh makes MuJoCo's compiler
# hard-error ("has coplanar vertices, cannot compute convex hull") -- see
# the first kitchen import's own version of this script for the same issue.
# Merging by material (rather than by individual object) makes this far
# less likely here (a material shared across many differently-oriented
# parts is unlikely to stay perfectly coplanar overall), so this is a
# defensive backstop, not an expected common case.
_MIN_EXTENT_M = 0.003


# Hand-picked color corrections for materials whose own Kd renders as a
# dull, muddy approximation of something identifiable in the reference
# renders (model/kitchen/kitchen-scene-*.webp) -- found by cross-referencing
# each material's own mesh position (via trimesh, against the room's real
# floor plan) with what actually sits there in those renders, not guessed
# from the material name alone. Kd itself is left alone for anything that
# already reads correctly (most of the 106 kept materials do) -- this is a
# short list of specific, confirmed mismatches, not a blanket recolor.
_MATERIAL_OVERRIDES: dict[str, tuple[float, float, float, float]] = {
    # The potted herbs/plant by the window (Material__2/5/9/11, clustered
    # around x=-3.15..-3.47, y=1.86..2.26 in the final room frame) and the
    # small plant on the island itself (Material_2, x=-1.4..-1.84,
    # y=2.22..2.64) -- a dark, saturated green per the user's own correction
    # (an earlier, lighter green pass wasn't dark enough).
    "Material__2": (0.10, 0.32, 0.12, 1.0),
    "Material__5": (0.07, 0.24, 0.09, 1.0),
    "Material__9": (0.13, 0.36, 0.15, 1.0),
    "Material__11": (0.09, 0.34, 0.11, 1.0),
    "Material_2": (0.10, 0.32, 0.12, 1.0),
    # Material_3 (x=-1.70..-1.55, y=2.38..2.53, ~15cm, right at the base of
    # the island plant above -- i.e. its pot, not a separate fruit bowl as
    # an earlier pass here guessed) -- the user's own description ("shows
    # its mud on top, need to be brown") confirms this reads as the potting
    # soil/terracotta container, not fruit -- a real fruit bowl's geometry
    # was searched for exhaustively (position cross-referencing across the
    # whole island, live raycasting) and no separate matching object was
    # found; it likely doesn't exist as distinct geometry in this export.
    "Material_3": (0.45, 0.30, 0.20, 1.0),
    # Backsplash tile strip (Bricks_Tiles_D01_50cm) -- was a near-black Kd
    # (0.035), reference renders show white subway tile there.
    "Bricks_Tiles_D01_50cm": (0.90, 0.89, 0.86, 1.0),
    # Countertop marble (both the wall counters and the island top share this
    # one material) was left at its own near-flat Kd (0.886,0.890,0.878) --
    # almost the identical shade as the wall's own Stucco (0.882 flat gray),
    # so counter and wall read as one continuous blob with no edge definition
    # ("tables look blunt"). A cleaner, brighter white marble tone gives the
    # countertops their own distinct read against the wall and cabinets.
    "Cozinha_Bancada_Marmore_Biancone_120cm": (0.95, 0.95, 0.94, 1.0),
    # The kitchen sink's own basin+faucet material is handled separately,
    # split by height -- see _SPLIT_BY_HEIGHT below -- since the user wants
    # the basin and the tap/spout different colors, not achievable with one
    # flat override here.
    # Faucet/trim chrome (Steel_Polished appears at the tap and elsewhere as
    # scattered trim; "chrome" and "stainless_steel_aluminium" likewise) --
    # already a plausible silver, just brightened for a more polished-chrome
    # pop per the user's own ask.
    "Steel_Polished": (0.85, 0.86, 0.87, 1.0),
    "Steel_Polished_2": (0.85, 0.86, 0.87, 1.0),
    "Steel_Polished_3": (0.85, 0.86, 0.87, 1.0),
    "chrome": (0.88, 0.89, 0.90, 1.0),
    "stainless_steel_aluminium": (0.85, 0.86, 0.87, 1.0),
    # The row of small cylindrical spice jars on the open wall shelf (two
    # clusters found by position, both at shelf height next to the range
    # hood: Standardmaterial/1/4/5 and _22/14/_24) -- muddy, low-saturation
    # Kd by default; richer, more distinct spice colors per the user's own
    # "more vibrant and classy" ask. Can't change these parts' actual
    # shininess/finish -- every kitchen geom shares one roughness/metalness
    # setting in loadHumanoidScene.ts, there's no per-object finish control
    # yet -- but alpha *is* per-geom (see loadHumanoidScene.ts's own
    # `transparent: color[3] < 1.0` handling, already used for the window
    # fix below), so the actual jar bodies (Standardmaterial2/6, found after
    # this first pass -- see their own comment) get real transparency too.
    "Standardmaterial": (0.58, 0.20, 0.09, 1.0),
    "Standardmaterial1": (0.80, 0.60, 0.08, 1.0),
    "Standardmaterial4": (0.38, 0.46, 0.18, 1.0),
    "Standardmaterial5": (0.85, 0.45, 0.06, 1.0),
    "_22": (0.78, 0.50, 0.10, 1.0),
    "Standardmaterial14": (0.65, 0.18, 0.09, 1.0),
    "_24": (0.72, 0.55, 0.13, 1.0),
    # Standardmaterial2/6 -- same shelf position (x=-2.47, y=4.27) as the
    # jar-accent materials just above, but these two are the actual jar
    # *bodies* (much bigger pieces, 10656 and 3888 faces) and were still
    # pure black Kd, which is why the shelf still read as "all black jars"
    # after the first pass only recolored the smaller lid/rim/accent parts
    # at that same spot. Translucent amber glass, per the user's own
    # "glassy... spices showing through in yellow, brown colors" ask.
    "Standardmaterial2": (0.75, 0.45, 0.12, 0.4),
    "Standardmaterial6": (0.7, 0.4, 0.1, 0.4),
    # Main room floor -- was a pale, washed-out tan (0.82,0.65,0.47) that
    # reads as gray in-engine; the reference photos (kitchen-scene-day-view)
    # show a warmer, more saturated honey-oak plank floor (sampled directly
    # off the reference image in direct light: ~rgb(180,118,84)).
    "Flooring_Parquet_Parallel_H01_120cm": (0.70, 0.46, 0.32, 1.0),
    # The island's own paneled front (name literally means "wood island
    # countertop" in Portuguese) was left at a stray near-white Kd (0.882)
    # instead of the wood tone its own name implies -- the user's own report
    # ("drawers of middle table... completely white"). One material covers
    # both the vertical plank facing (59 thin pieces, all at the same
    # y=2.08..2.09 sliver -- one flat face of the island) and its low
    # toe-kick strip, so a flat override recolors the whole visible front at
    # once. First pass used a distinct-but-similar brown; the user's own
    # follow-up asked for it to match the side-counter cabinets exactly, so
    # this is now the identical rgba as Wood_Mahogany_33_46_100cm below.
    "Cozinha_Ilha_Madeira_Bancada_280x50cm": (0.325, 0.165, 0.078, 1.0),
    # The island's actual drawer/cabinet fronts (the working side facing the
    # sink, not the plank paneling above) are a separate material entirely
    # -- "Formica" white left un-recolored, plus a thin trim strip between
    # it and the paneling (Alvenaria_Branca) that reads as an odd pale gap
    # otherwise. The user's own follow-up: "center table drawers are in
    # white color make them in same color as rest of the shelfs and
    # cabinates." Same rgba as the wall cabinetry, for the same reason as
    # the island paneling above.
    "Cozinha_Gabinetes_Frente_Formica": (0.325, 0.165, 0.078, 1.0),
    "Cozinha__Gabinete_Lixeira_Formica_Branca": (0.325, 0.165, 0.078, 1.0),
    "Alvenaria_Branca": (0.325, 0.165, 0.078, 1.0),
}

# The counter appliances by the window (juicer at x=-3.28,y=2.85..3.35 and
# what reads as a coffee machine at x=-3.15..-3.25,y=3.6..3.85) are both
# hidden inside "FrontColor" like the fruit bowl/cup/plate were (see
# _classify_frontcolor_piece's own comment) -- small pieces the whole-file
# material merge fused into the room-spanning cabinet-front white. Found by
# searching FrontColor's connected components for the two tight clusters
# sitting on the counter just past the window, then sub-classifying each
# cluster's own pieces by height: reference photos show both appliances as
# a dark/metal body with a contrasting band, not one flat color, and this
# source geometry happens to split the same way (a flat low base, a tall
# main body, and separate thin pieces right at the very top for the
# lid/head) -- close enough to bucket by z without per-piece guessing.
_JUICER_REGION = ((-3.50, -3.05), (2.80, 3.35), (0.85, 1.35))
_COFFEE_MACHINE_REGION = ((-3.50, -2.95), (3.55, 3.85), (0.85, 1.35))

# The sink basin and its own faucet/spout share one material
# ("Pia_Cozinha_Dupla_Quadrada_050_Mater_02" -- Portuguese for "kitchen
# sink") in the source file, but the user wants them different colors (black
# basin, silver tap) -- a flat _MATERIAL_OVERRIDES entry can't do that, since
# it colors the whole material one way. Confirmed via trimesh's
# split(): the basin's own connected component sits at world z=0.63..0.88
# (counter height), while the spout/handle pieces sit at z=1.05..1.33
# (rising above the counter) -- cleanly separable by height, no z range
# in between. Each entry: (height threshold, rgba below it, rgba above it).
_SPLIT_BY_HEIGHT: dict[str, tuple[float, tuple, tuple]] = {
    "Pia_Cozinha_Dupla_Quadrada_050_Mater_02": (
        0.95,
        (0.06, 0.06, 0.07, 1.0),  # basin: black
        (0.85, 0.86, 0.87, 1.0),  # spout/handle: silver
    ),
}

# The window ("White_Milgard") is opaque white (Kd ~1,1,1, alpha 1.0) for
# every one of its ~73 connected components -- frame, mullions, hardware,
# *and* the glass panes themselves all render as one solid white shape, so
# the actual window reads as just another wall panel instead of glass (the
# user's own report: "it looks like the wall itself"). trimesh's split()
# shows the frame/hardware pieces are all tiny (1-48 faces: bolts, muntins,
# corner brackets), while the two actual glass panes (one per window) are
# the standout large pieces (909 and 939 faces) -- split by a face-count
# threshold, not position, since both windows' glass need the same
# treatment. Glass gets real alpha transparency (this app's renderer does
# support per-geom opacity, see loadHumanoidScene.ts's own
# `transparent: color[3] < 1.0` handling) plus a saturated blue tint (see
# that tuple's own comment on why faint didn't read as glass); the frame
# stays opaque white.
_SPLIT_GLASS_BY_SIZE: dict[str, tuple[int, tuple, tuple]] = {
    "White_Milgard": (
        100,
        (1.0, 1.0, 1.0, 1.0),  # frame/hardware (small pieces): opaque white
        (0.32, 0.58, 0.72, 0.4),  # glass panes (large pieces): saturated blue, more visible
        # ^ a faint (0.75,0.85,0.88 @ alpha 0.18) tint was confirmed live to
        # be indistinguishable from the wall right behind it -- there's no
        # exterior scenery to see "through" the glass into (this room has no
        # outside world modeled), and the wall's own Stucco color is a
        # similarly pale warm gray, so a subtle glass tint just reads as
        # "same wall, slightly duller" instead of "different material,
        # transparent." A clearly saturated blue at a more present alpha
        # reads as glass on its own merits, not by contrast with a view
        # through it.
    ),
}

# The one real west-wall window (the fridge-side window the user kept
# reporting as "still looks like a wall", then "doesn't look like the window
# behind the stairs") has a genuine glass pane (White_Milgard_glass, split
# out above) sitting in its reveal -- but the room-facing surface of
# Stucco_A02_Color_50cm_White is a single ~22000-face merged mesh spanning
# every wall *and* the ceiling, and at this exact opening its own
# triangulation is broken: several of its fan-triangulated faces (all
# sharing one apex vertex out at y=4.4986,z=0.8763) sweep straight across
# the window's own rectangle instead of stopping at its edges, so an opaque
# white triangle sits directly between the room and the glass (confirmed by
# a manual ray-triangle cast from the live three.js scene: the nearest hit
# at the window's own screen position was this Stucco face, not the glass
# behind it). A first attempt papered over this with a small synthetic
# glass-colored patch flush with the wall -- structurally fine, but it also
# blocked the real glass's own mullion bars from showing through, which is
# exactly why this window read as a flat, undivided pane next to the
# working stairs window (same source geometry, no broken wall there) that
# has visible dividers. Real fix: clip the actual offending Stucco faces
# against the window's rectangle (2D polygon difference in the wall's own
# y-z plane, re-triangulated) so the room-facing wall has a genuine hole
# there instead of a patch in front of it -- see _cut_stucco_window_hole().
_STUCCO_WINDOW_HOLE_PLANE_X = -3.515
_STUCCO_WINDOW_HOLE_RECT_YZ = ((1.7413, 2.9596), (1.1808, 2.4000))


def _cut_stucco_window_hole(verts: np.ndarray, faces: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    (wy0, wy1), (wz0, wz1) = _STUCCO_WINDOW_HOLE_RECT_YZ
    window_rect = shapely_box(wy0, wz0, wy1, wz1)
    plane_x = _STUCCO_WINDOW_HOLE_PLANE_X

    on_plane = np.all(np.abs(verts[faces][:, :, 0] - plane_x) < 0.01, axis=1)
    candidate_idxs = set(np.where(on_plane)[0].tolist())

    out_verts = [verts]
    out_faces = []
    for i, face in enumerate(faces):
        if i not in candidate_idxs:
            out_faces.append(face)
            continue
        tri2d = verts[face][:, [1, 2]]
        poly = Polygon(tri2d)
        if not poly.is_valid or poly.area < 1e-9 or not poly.intersects(window_rect):
            out_faces.append(face)
            continue
        diff = poly.difference(window_rect)
        if diff.is_empty:
            continue  # this face's entire area is inside the window opening
        pieces = list(diff.geoms) if diff.geom_type == "MultiPolygon" else [diff]
        for piece in pieces:
            if piece.area < 1e-7:
                continue
            verts2d, tris = trimesh.creation.triangulate_polygon(piece, engine="earcut")
            base_idx = sum(len(vv) for vv in out_verts)
            out_verts.append(np.column_stack([np.full(len(verts2d), plane_x), verts2d]))
            for t in tris:
                out_faces.append(t + base_idx)

    return np.concatenate(out_verts), np.array(out_faces)


# "FrontColor" is mostly cabinet-door fronts scattered across the whole
# kitchen (its own combined bounding box is ~7x6x4m, see this file's own
# history), but it also happens to be the material used for the island's
# fruit bowl + fruit, and a separate cup + plate + utensil group right next
# to the sink -- exactly the "bowl, coffee cup, plate of bread" cluster the
# user asked about, found by searching this material's own connected
# components for anything small sitting near the sink/island rather than
# spread across the room. Everything here stayed the cabinet-front's own
# flat white, which is why it read as invisible/uncolored.
#
# _classify_frontcolor_piece(piece) -> (suffix, rgba) for a piece to
# extract with its own color, or None to leave it as plain cabinet-front
# white. Region-and-shape based (bounding box position, plus roundish vs.
# flat vs. elongated proportions), not per-piece-index -- trimesh's split()
# order isn't guaranteed stable across reruns, but which small, real-world
# region of the kitchen a piece's own geometry sits in, and roughly what
# shape it is, will be.
_FRUIT_BOWL_REGION = ((0.35, 0.75), (2.25, 2.55), (0.85, 1.15))
_CUP_PLATE_REGION = ((0.15, 0.65), (1.75, 2.05), (0.85, 1.05))
_BOOK_REGION = ((-1.10, -0.70), (1.70, 2.00), (0.85, 1.05))
# The corner cabinet box connecting the west-wall open shelf (by the
# window/jars) to the north-wall open shelf (above the range) -- one
# 0.6x0.6x0.9m block, plain cabinet-front white where every other cabinet
# surface around it is the wood-toned cabinetry. The user's own report:
# "the shelf connecting front wall's shelf and left wall's shelf looks
# white... make it brown as well."
_SHELF_CONNECTOR_REGION = ((-3.50, -2.60), (3.80, 4.50), (1.40, 2.40))


def _region_contains(center, region) -> bool:
    (x0, x1), (y0, y1), (z0, z1) = region
    return x0 <= center[0] <= x1 and y0 <= center[1] <= y1 and z0 <= center[2] <= z1


def _classify_frontcolor_piece(piece, piece_index: int):
    b = piece.bounds
    center = (b[0] + b[1]) / 2
    ext = b[1] - b[0]

    if _region_contains(center, _FRUIT_BOWL_REGION):
        # The bowl itself is the one clearly biggest, widest, flattish piece
        # in this cluster (0.37x0.37x0.14m); everything else at this same
        # spot is an individual piece of fruit -- alternate red/yellow
        # (apple/banana, per the user's own ask) since there's no reliable
        # per-fruit shape signal to pick a color from otherwise.
        if max(ext[0], ext[1]) > 0.3:
            return "bowl", (0.82, 0.83, 0.84, 0.55)  # glass bowl, translucent
        return ("fruit_red", (0.72, 0.10, 0.08, 1.0)) if piece_index % 2 == 0 else ("fruit_yellow", (0.88, 0.72, 0.10, 1.0))

    if _region_contains(center, _CUP_PLATE_REGION):
        # This whole cluster (plate + cup assembly + a fork, a knife, two
        # bread slices, and a two-layer pancake stack, all merged into
        # FrontColor) was untangled piece by piece with a one-off debug
        # pass -- render every piece here in its own bright, unique color,
        # screenshot it live, and read off which shape is which by eye.
        # Bounding-box proportions alone can't tell a fork from a bread
        # slice from a stack of pancakes; this can't be guessed from shape
        # heuristics -- see the per-piece extents keyed below, matched by
        # eye against that render:
        #   E (0.257,0.257,0.019) plate -- the big flat disc
        #   B (0.154,0.154,0.016) saucer -- round, sits under the cup
        #   K (0.093,0.102,0.036) bread slice 1 -- rectangular
        #   C (0.120,0.122,0.032) bread slice 2 -- rectangular, overlaps K
        #   A (0.088,0.172,0.025) fork -- tines visible in the render
        #   D (0.017,0.185,0.018) knife -- thin and long
        #   I (0.105,0.105,0.012) pancake stack, top face
        #   J (0.108,0.108,0.012) pancake stack, side/lower layer
        key = tuple(round(e, 3) for e in ext)
        colors = {
            (0.257, 0.257, 0.019): ("plate", (0.94, 0.92, 0.87, 1.0)),
            (0.154, 0.154, 0.016): ("saucer", (0.94, 0.92, 0.87, 1.0)),
            (0.093, 0.102, 0.036): ("bread1", (0.55, 0.35, 0.18, 1.0)),
            (0.12, 0.122, 0.032): ("bread2", (0.55, 0.35, 0.18, 1.0)),
            (0.088, 0.172, 0.025): ("fork", (0.8, 0.81, 0.82, 1.0)),
            (0.017, 0.185, 0.018): ("knife", (0.8, 0.81, 0.82, 1.0)),
            (0.105, 0.105, 0.012): ("pancake_top", (0.85, 0.6, 0.56, 1.0)),
            (0.108, 0.108, 0.012): ("pancake_side", (0.85, 0.6, 0.56, 1.0)),
        }
        if key in colors:
            return colors[key]
        return "cup", (0.36, 0.20, 0.09, 1.0)

    if _region_contains(center, _JUICER_REGION):
        # The juicer's own flat red/orange base sits lowest (z<1.0); its lid
        # and the small clasp/valve pieces right at the top (z>=1.18) are
        # black; everything in between is the tall steel canister body.
        if b[1][2] < 1.0:
            return "juicer_base", (0.80, 0.24, 0.05, 1.0)
        if b[0][2] >= 1.18:
            return "juicer_lid", (0.07, 0.07, 0.08, 1.0)
        return "juicer_body", (0.80, 0.81, 0.83, 1.0)

    if _region_contains(center, _BOOK_REGION):
        # The book/magazine by the sink (four overlapping flat pieces --
        # cover, page block, back cover, a thin bookmark or second slim
        # book) was left plain cabinet white -- the user's own report ("raw
        # white color") plus a follow-up that these read as more of a
        # stack of novels than one book, so distinct cover colors rather
        # than one flat recolor. The thickest piece is the page block
        # itself (warm cream, like paper) rather than a cover color; the
        # thinnest is treated as its own separate slim book.
        if ext[2] > 0.04:
            return "book_pages", (0.93, 0.88, 0.78, 1.0)
        if ext[2] < 0.015:
            return "book_navy", (0.10, 0.16, 0.38, 1.0)
        return "book_cover", (0.45, 0.11, 0.12, 1.0)

    if _region_contains(center, _SHELF_CONNECTOR_REGION):
        return "shelf_connector", (0.325, 0.165, 0.078, 1.0)

    if _region_contains(center, _COFFEE_MACHINE_REGION):
        # Main body (base + housing, z<1.08) and the head right at the top
        # (z>=1.20) are black, matching the reference's black machine body;
        # the thin band in between (drip tray / trim) is steel.
        if b[0][2] < 1.08:
            return "coffeemachine_body", (0.06, 0.06, 0.07, 1.0)
        if b[0][2] >= 1.20:
            return "coffeemachine_top", (0.06, 0.06, 0.07, 1.0)
        return "coffeemachine_trim", (0.80, 0.81, 0.83, 1.0)

    return None


# A second, separate cluster of spice jars sits on the shelf just above the
# ones already fixed (_MATERIAL_OVERRIDES' Standardmaterial* entries, at
# z~1.5-1.8) -- five identical tall jar shapes at z~2.0-2.2, all still
# merged into one pure-black material (Material__4010, along with a couple
# of unrelated ceramic canister lids sharing the same name elsewhere on the
# shelf). The user's own report: "front wall upper shelf jars still looks
# black... make them look similar to lower shelf jars." Jars are identified
# by their own proportions (tall cylinders, ~0.13x0.13x0.21m) rather than
# position alone, since the canister lids sharing this material sit at a
# different x (the Oats/Flour canisters) but a similar height band.
_UPPER_JAR_HEIGHT_RANGE = (0.19, 0.22)
_UPPER_JAR_COLORS = [
    (0.75, 0.45, 0.12, 0.45),  # amber glass, matching the lower shelf's jar bodies
    (0.55, 0.30, 0.08, 0.45),  # darker amber
    (0.70, 0.55, 0.15, 0.45),  # golden
    (0.35, 0.40, 0.12, 0.45),  # olive
    (0.60, 0.15, 0.08, 0.45),  # paprika red
]


def _classify_upper_jar_piece(piece, piece_index: int):
    ext = piece.bounds[1] - piece.bounds[0]
    lo, hi = _UPPER_JAR_HEIGHT_RANGE
    if lo <= ext[2] <= hi and max(ext[0], ext[1]) < 0.16:
        return f"jar{piece_index}", _UPPER_JAR_COLORS[piece_index % len(_UPPER_JAR_COLORS)]
    # Leftover pieces at this same material (canister lids/knobs elsewhere
    # on the shelf) -- a plain dark neutral instead of pure black, matching
    # the other canister lids (Oats/Flour) already on that shelf.
    return "lid", (0.22, 0.21, 0.20, 1.0)


# The range (cooktop on top, oven door below -- what the user calls "the
# cook top on front wall's attached table" and "the microwave below that")
# has its entire body shell -- door, sides, control panel, knobs, all of
# it -- on one material, Steel_Polished_2, which an earlier pass in this
# same file already brightened into a shiny chrome for the sink faucet
# elsewhere (a *different*, unrelated material, "Steel_Polished" with no
# suffix -- this one, "_2", turned out to belong entirely to the range).
# The user wants the body black with the knobs/handle/frame staying
# silver, not the reverse. The range hood further up (z>=1.2) shares this
# same material too but was never part of the complaint and already
# matches the reference photos as brushed steel, so it's left alone. The
# knobs/control-panel band was found by inspecting this material's own
# piece heights directly (~90 small pieces cluster tightly at z=0.7-0.9,
# the control panel; everything below is the door/body).
def _classify_range_piece(piece):
    b = piece.bounds
    z_center = (b[0][2] + b[1][2]) / 2
    if z_center >= 1.2:
        return "hood", (0.85, 0.86, 0.87, 1.0)
    if 0.55 <= z_center <= 1.15:
        return "controls", (0.85, 0.86, 0.87, 1.0)
    return "body", (0.05, 0.05, 0.05, 1.0)


def _safe_name(material_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]+", "_", material_name).strip("_").lower()


def main() -> None:
    scene = trimesh.load(str(OBJ_PATH), process=False, group_material=True, skip_materials=False)
    assert isinstance(scene, trimesh.Scene), f"expected a multi-material Scene, got {type(scene)}"

    MESHES_DIR.mkdir(exist_ok=True)
    for old in MESHES_DIR.glob("*.stl"):
        old.unlink()

    ROTATION = np.array([[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]])
    assert abs(np.linalg.det(ROTATION) - 1.0) < 1e-9, "must be a proper rotation, not a mirror"

    # Recenter pass: first transform every kept mesh's vertices (rotation
    # only), track the combined bounds, then re-export with the centering
    # translation applied -- two passes over the geometry (cheap relative to
    # the STL export itself) rather than hardcoding a translation guessed
    # from a one-off bounds printout, so this stays correct if the source
    # OBJ is ever swapped for a revised export with different dimensions.
    prepared = []
    mins, maxs = [], []
    for name, geom in scene.geometry.items():
        material_name = getattr(geom.visual.material, "name", None) or "unknown"
        if material_name in _SKIP_MATERIALS:
            continue
        verts = geom.vertices @ ROTATION.T
        if (verts.max(axis=0) - verts.min(axis=0)).min() < _MIN_EXTENT_M:
            continue
        prepared.append((material_name, verts, geom.faces, geom.visual.material))
        mins.append(verts.min(axis=0))
        maxs.append(verts.max(axis=0))

    combined_min = np.min(mins, axis=0)
    combined_max = np.max(maxs, axis=0)
    offset = -(combined_min + combined_max) / 2
    offset[2] = -combined_min[2]  # floor flush with world z=0, not vertically recentered
    # The room's own bounding-box center (what a plain recenter would put at
    # the origin) lands inside the kitchen island/counter cluster itself --
    # this source file's footprint includes a hallway/staircase extension
    # well past the kitchen (see this module's own docstring on the room's
    # real dimensions), which skews the geometric center away from any open
    # floor. Checked directly (real mesh vertices, not just bounding boxes,
    # against a robot-sized column from z=0.05 to 1.6m): the plain-centered
    # origin has real geometry (marble counter, sink, cabinets) overlapping
    # it, while a further 2.5m shift toward the open dining-area side (+y,
    # since -y is where the counters/island sit) is clear. This constant is
    # that empirically-checked correction, not a guess.
    offset[1] += 2.5
    print(f"room bounds before centering: {combined_min} .. {combined_max}")
    print(f"applying offset: {offset}")

    def _split_and_export(material_name, verts, faces, i, predicate, suffix_a, rgba_a, suffix_b, rgba_b, manifest):
        """Split one material's combined mesh by connected component,
        bucket each piece into group A or B by `predicate(piece)`, then
        re-merge and export each group as its own STL/manifest entry with
        its own rgba. Shared by _SPLIT_BY_HEIGHT (sink/tap) and
        _SPLIT_GLASS_BY_SIZE (window frame/glass) -- same
        split-bucket-merge-export shape, different bucketing rule.

        process=True here (unlike everywhere else in this script, which
        deliberately keeps process=False) is required for split() to mean
        anything: this source data has no shared vertex indices between
        adjacent triangles, so with process=False, split() treats every
        single triangle as its own disconnected "piece" (confirmed:
        _SPLIT_GLASS_BY_SIZE's face-count bucketing silently found zero
        pieces over the threshold this way -- every "piece" was 1-2
        triangles). The height split still happened to produce correct
        results without this (each fragment's own z position is right
        either way), which is why the bug wasn't visible until a
        size-based split needed real connected components. Welding first
        restores them -- the actual glass panes come back as the ~900-face
        pieces a direct check against this geometry expects."""
        whole = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
        pieces = whole.split(only_watertight=False)
        verts_a, faces_a, verts_b, faces_b = [], [], [], []
        for piece in pieces:
            if predicate(piece):
                offset_idx = sum(len(v) for v in verts_a)
                verts_a.append(piece.vertices)
                faces_a.append(piece.faces + offset_idx)
            else:
                offset_idx = sum(len(v) for v in verts_b)
                verts_b.append(piece.vertices)
                faces_b.append(piece.faces + offset_idx)
        for suffix, vs, fs, rgba in [(suffix_a, verts_a, faces_a, rgba_a), (suffix_b, verts_b, faces_b, rgba_b)]:
            if not vs:
                continue
            out_name = f"kitchen_{_safe_name(material_name)}_{suffix}_{i}"
            out_mesh = trimesh.Trimesh(vertices=np.concatenate(vs), faces=np.concatenate(fs), process=False)
            out_mesh.export(MESHES_DIR / f"{out_name}.stl")
            manifest.append({"file": f"{out_name}.stl", "material": f"{material_name}_{suffix}", "rgba": list(rgba)})

    manifest = []
    for i, (material_name, verts, faces, material) in enumerate(prepared):
        verts = verts + offset

        if material_name in _SPLIT_BY_HEIGHT:
            threshold, rgba_below, rgba_above = _SPLIT_BY_HEIGHT[material_name]
            _split_and_export(
                material_name, verts, faces, i,
                lambda p, t=threshold: p.bounds[0][2] < t,
                "below", rgba_below, "above", rgba_above, manifest,
            )
            continue

        if material_name in _SPLIT_GLASS_BY_SIZE:
            face_threshold, rgba_frame, rgba_glass = _SPLIT_GLASS_BY_SIZE[material_name]
            _split_and_export(
                material_name, verts, faces, i,
                lambda p, t=face_threshold: len(p.faces) < t,
                "frame", rgba_frame, "glass", rgba_glass, manifest,
            )
            continue

        if material_name == "FrontColor":
            # Same split/export shape as _split_and_export above, but N-way
            # (bowl/fruit/plate/cup/utensil, or left as plain cabinet-front
            # white) instead of a single 2-way predicate -- see
            # _classify_frontcolor_piece's own comment.
            whole = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
            pieces = whole.split(only_watertight=False)
            buckets: dict[str, tuple[list, list, tuple]] = {}
            default_verts, default_faces = [], []
            for pi, piece in enumerate(pieces):
                classified = _classify_frontcolor_piece(piece, pi)
                if classified is None:
                    offset_idx = sum(len(v) for v in default_verts)
                    default_verts.append(piece.vertices)
                    default_faces.append(piece.faces + offset_idx)
                    continue
                suffix, rgba = classified
                if suffix not in buckets:
                    buckets[suffix] = ([], [], rgba)
                bvs, bfs, _ = buckets[suffix]
                offset_idx = sum(len(v) for v in bvs)
                bvs.append(piece.vertices)
                bfs.append(piece.faces + offset_idx)
            buckets["_default"] = (default_verts, default_faces, (1.0, 1.0, 1.0, 1.0))
            for suffix, (vs, fs, rgba) in buckets.items():
                if not vs:
                    continue
                out_name = f"kitchen_{_safe_name(material_name)}_{suffix}_{i}"
                out_mesh = trimesh.Trimesh(vertices=np.concatenate(vs), faces=np.concatenate(fs), process=False)
                out_mesh.export(MESHES_DIR / f"{out_name}.stl")
                manifest.append({"file": f"{out_name}.stl", "material": f"{material_name}{suffix}", "rgba": list(rgba)})
            continue

        if material_name == "Material__4010":
            # Same N-way split shape as FrontColor above -- see
            # _classify_upper_jar_piece's own comment.
            whole = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
            pieces = whole.split(only_watertight=False)
            jar_buckets: dict[str, tuple[list, list, tuple]] = {}
            for pi, piece in enumerate(pieces):
                suffix, rgba = _classify_upper_jar_piece(piece, pi)
                if suffix not in jar_buckets:
                    jar_buckets[suffix] = ([], [], rgba)
                bvs, bfs, _ = jar_buckets[suffix]
                offset_idx = sum(len(v) for v in bvs)
                bvs.append(piece.vertices)
                bfs.append(piece.faces + offset_idx)
            for suffix, (vs, fs, rgba) in jar_buckets.items():
                if not vs:
                    continue
                out_name = f"kitchen_{_safe_name(material_name)}_{suffix}_{i}"
                out_mesh = trimesh.Trimesh(vertices=np.concatenate(vs), faces=np.concatenate(fs), process=False)
                out_mesh.export(MESHES_DIR / f"{out_name}.stl")
                manifest.append({"file": f"{out_name}.stl", "material": f"{material_name}{suffix}", "rgba": list(rgba)})
            continue

        if material_name == "Steel_Polished_2":
            # Same N-way split shape as above -- see _classify_range_piece's
            # own comment.
            whole = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
            pieces = whole.split(only_watertight=False)
            range_buckets: dict[str, tuple[list, list, tuple]] = {}
            for piece in pieces:
                suffix, rgba = _classify_range_piece(piece)
                if suffix not in range_buckets:
                    range_buckets[suffix] = ([], [], rgba)
                bvs, bfs, _ = range_buckets[suffix]
                offset_idx = sum(len(v) for v in bvs)
                bvs.append(piece.vertices)
                bfs.append(piece.faces + offset_idx)
            for suffix, (vs, fs, rgba) in range_buckets.items():
                if not vs:
                    continue
                out_name = f"kitchen_{_safe_name(material_name)}_{suffix}_{i}"
                out_mesh = trimesh.Trimesh(vertices=np.concatenate(vs), faces=np.concatenate(fs), process=False)
                out_mesh.export(MESHES_DIR / f"{out_name}.stl")
                manifest.append({"file": f"{out_name}.stl", "material": f"{material_name}{suffix}", "rgba": list(rgba)})
            continue

        if material_name == "Stucco_A02_Color_50cm_White":
            verts, faces = _cut_stucco_window_hole(verts, faces)

        out_name = f"kitchen_{_safe_name(material_name)}_{i}"
        out_mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=False)
        out_mesh.export(MESHES_DIR / f"{out_name}.stl")

        if material_name in _MATERIAL_OVERRIDES:
            rgba = _MATERIAL_OVERRIDES[material_name]
        else:
            diffuse = getattr(material, "diffuse", None)
            if diffuse is not None:
                rgba = (diffuse[0] / 255, diffuse[1] / 255, diffuse[2] / 255, diffuse[3] / 255 if len(diffuse) > 3 else 1.0)
            else:
                rgba = (0.8, 0.8, 0.8, 1.0)

        manifest.append({"file": f"{out_name}.stl", "material": material_name, "rgba": list(rgba)})

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2))
    print(f"kept {len(manifest)} of {len(scene.geometry)} materials ({len(_SKIP_MATERIALS)} excluded by name)")
    print(f"wrote {len(manifest)} STL files -> {MESHES_DIR}")
    print(f"wrote manifest -> {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
